version: "3.8"

services:
  db:
    image: postgres
    container_name: map-test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: postgresql
    restart: unless-stopped
